screencopy: add missing header for sdbus-cpp 1.5.0
src/portals/Screencopy.cpp:956:9: error: use of undeclared identifier 'close'
        close(PBUFFER->fd[plane]);
        ^
src/portals/Screencopy.cpp:1293:21: error: use of undeclared identifier 'close'
                    close(pBuffer->fd[plane_tmp]);
                    ^
src/portals/Screencopy.cpp:1308:17: error: use of undeclared identifier 'close'
                close(pBuffer->fd[plane]);
                ^